var good=[];
good.push({name:"10-Yard Fight	"});
good.push({name:"1942	"});
good.push({name:"1943 - The Battle of Midway	"});
good.push({name:"1991 Du Ma Racing	"});
good.push({name:"1999 - Hore, Mitakotoka! Seikimatsu	"});
good.push({name:"3-D Battles of World Runner, The	"});
good.push({name:"3D Block	"});
good.push({name:"4 Nin Uchi Mahjong	"});
good.push({name:"720	"});
good.push({name:"75 Bingo	"});
good.push({name:"8 Eyes	"});
good.push({name:"'89 Dennou Kyuusei Uranai	"});
good.push({name:"A Ressha de Ikou	"});
good.push({name:"Aa Yakyuu Jinsei Icchokusen	"});
good.push({name:"Abadox - The Deadly Inner War	"});
good.push({name:"Action 52	"});
good.push({name:"Addams Family, The	"});
good.push({name:"Addams Family, The - Pugsley's Scavenger Hunt	"});
good.push({name:"Advanced Dungeons & Dragons - Dragon Strike	"});
good.push({name:"Advanced Dungeons & Dragons - Dragons of Flame	"});
good.push({name:"Advanced Dungeons & Dragons - Heroes of the Lance	"});
good.push({name:"Advanced Dungeons & Dragons - Hillsfar	"});
good.push({name:"Advanced Dungeons & Dragons - Pool of Radiance	"});
good.push({name:"Adventures in the Magic Kingdom	"});
good.push({name:"Adventures of Bayou Billy, The	"});
good.push({name:"Adventures of Captain Comic, The	"});
good.push({name:"Adventures of Dino Riki, The	"});
good.push({name:"Adventures of Dr. Franken, The	"});
good.push({name:"Adventures of Gilligan's Island, The	"});
good.push({name:"Adventures of Lolo	"});
good.push({name:"Adventures of Lolo 2	"});
good.push({name:"Adventures of Lolo 3	"});
good.push({name:"Adventures of Rad Gravity, The	"});
good.push({name:"Adventures of Rocky and Bullwinkle and Friends, The	"});
good.push({name:"Adventures of Tom Sawyer	"});
good.push({name:"After Burner	"});
good.push({name:"Ai Sensei no Oshiete - Watashi no Hoshi	"});
good.push({name:"Ai Senshi Nicol	"});
good.push({name:"Aigiina no Yogen - From The Legend of Balubalouk	"});
good.push({name:"Air Fortress	"});
good.push({name:"Airwolf (J)	"});
good.push({name:"Airwolf (UE)	"});
good.push({name:"Akagawa Jirou no Yuurei Ressha	"});
good.push({name:"Akira	"});
good.push({name:"Akumajou Special - Boku Dracula-kun	"});
good.push({name:"Akuma-kun - Makai no Wana	"});
good.push({name:"Al Unser Jr. Turbo Racing	"});
good.push({name:"Aladdin (E)	"});
good.push({name:"Aladdin (Pirate)	"});
good.push({name:"Aladdin 2 (Pirate)	"});
good.push({name:"Aladdin 3 (Pirate)	"});
good.push({name:"Alfred Chicken	"});
good.push({name:"Alien 3	"});
good.push({name:"Alien Syndrome	"});
good.push({name:"All-Pro Basketball	"});
good.push({name:"Alpha Mission	"});
good.push({name:"Amagon	"});
good.push({name:"America Daitouryou Senkyo	"});
good.push({name:"America Oudan Ultra Quiz - Shijou Saidai no Tatakai	"});
good.push({name:"American Dream	"});
good.push({name:"American Gladiators	"});
good.push({name:"Ankoku Shinwa - Yamato Takeru Densetsu	"});
good.push({name:"Antarctic Adventure	"});
good.push({name:"Anticipation	"});
good.push({name:"Aoki Ookami to Shiroki Mejika - Genchou Hishi	"});
good.push({name:"Arch Rivals - A BasketBrawl!	"});
good.push({name:"Architect for Dr. PC Jr.	"});
good.push({name:"Archon	"});
good.push({name:"Arctic	"});
good.push({name:"Argus	"});
good.push({name:"Arkanoid	"});
good.push({name:"Arkanoid II	"});
good.push({name:"Arkista's Ring	"});
good.push({name:"Armadillo	"});
good.push({name:"Artelius	"});
good.push({name:"Asmik-kun Land	"});
good.push({name:"Asterix	"});
good.push({name:"Astro Fang - Super Machine	"});
good.push({name:"Astro Robo Sasa	"});
good.push({name:"Astyanax	"});
good.push({name:"Athena	"});
good.push({name:"Athletic World	"});
good.push({name:"Atlantis no Nazo	"});
good.push({name:"Attack Animal Gakuen	"});
good.push({name:"Attack of the Killer Tomatoes	"});
good.push({name:"Aussie Rules Footy	"});
good.push({name:"Auto-Upturn	"});
good.push({name:"AV Hanafuda Club	"});
good.push({name:"AV Jiu Ji Ma Jiang 2	"});
good.push({name:"AV Mahjongg	"});
good.push({name:"AV Mei Shao Nv Zhan Shi	"});
good.push({name:"AV Strip Mahjong	"});
good.push({name:"Babel no Tou	"});
good.push({name:"Baby Boomer	"});
good.push({name:"Back to the Future	"});
good.push({name:"Back to the Future Part II & III	"});
good.push({name:"Bad Dudes	"});
good.push({name:"Bad News Baseball	"});
good.push({name:"Bad Street Brawler	"});
good.push({name:"Baken Hisshou Gaku - Gate In	"});
good.push({name:"Bakushou! Star Monomane Shitennou	"});
good.push({name:"Bakushou!! Ai no Gekijou	"});
good.push({name:"Bakushou!! Jinsei Gekijou	"});
good.push({name:"Bakushou!! Jinsei Gekijou 2	"});
good.push({name:"Bakushou!! Jinsei Gekijou 3	"});
good.push({name:"Balda	"});
good.push({name:"Balda (BBG)	"});
good.push({name:"Ball Story - Jong Yuk Chuen Suet Fa Jong II	"});
good.push({name:"Ballblazer	"});
good.push({name:"Balloon Fight	"});
good.push({name:"Baltron	"});
good.push({name:"Banana	"});
good.push({name:"Bananan Ouji no Daibouken	"});
good.push({name:"Bandai Golf - Challenge Pebble Beach	"});
good.push({name:"Bandit Kings of Ancient China	"});
good.push({name:"Bao Qing Tian	"});
good.push({name:"Bao Xiao Tien Guo (Explosion Sangokushi)	"});
good.push({name:"Barbie	"});
good.push({name:"Barcode World	"});
good.push({name:"Bard's Tale II, The - The Destiny Knight	"});
good.push({name:"Bard's Tale, The - Tales of the Unknown	"});
good.push({name:"Barker Bill's Trick Shooting	"});
good.push({name:"Base Wars	"});
good.push({name:"Baseball	"});
good.push({name:"Baseball Fighter	"});
good.push({name:"Baseball Simulator 1.000	"});
good.push({name:"Baseball Stars	"});
good.push({name:"Baseball Stars II	"});
good.push({name:"Bases Loaded	"});
good.push({name:"Bases Loaded 3	"});
good.push({name:"Bases Loaded 4	"});
good.push({name:"Bases Loaded II	"});
good.push({name:"Bashi Bazook - Morphoid Masher	"});
good.push({name:"Batman	"});
good.push({name:"Batman - Return of the Joker	"});
good.push({name:"Batman Returns	"});
good.push({name:"Batsu & Terii	"});
good.push({name:"Battle Baseball	"});
good.push({name:"Battle Chess	"});
good.push({name:"Battle City	"});
good.push({name:"Battle Fleet	"});
good.push({name:"Battle of Olympus, The	"});
good.push({name:"Battle Stadium - Senbatsu Pro Yakyuu	"});
good.push({name:"Battle Storm	"});
good.push({name:"Battle Tank	"});
good.push({name:"Battleship	"});
good.push({name:"Battletoads	"});
good.push({name:"Battletoads & Double Dragon - The Ultimate Team	"});
good.push({name:"BB Car	"});
good.push({name:"Beauty and the Beast	"});
good.push({name:"Be-Bop-Highschool - Koukousei Gokuraku Densetsu	"});
good.push({name:"Bee 52	"});
good.push({name:"Beetlejuice	"});
good.push({name:"Best Keiba - Derby Stallion	"});
good.push({name:"Best of the Best - Championship Karate	"});
good.push({name:"Best Play Pro Yakyuu	"});
good.push({name:"Best Play Pro Yakyuu '90	"});
good.push({name:"Best Play Pro Yakyuu II	"});
good.push({name:"Best Play Pro Yakyuu Special	"});
good.push({name:"Bible Adventures	"});
good.push({name:"Bible Buffet	"});
good.push({name:"Big Bird's Hide & Speak	"});
good.push({name:"Big Nose Freaks Out	"});
good.push({name:"Big Nose the Caveman	"});
good.push({name:"Bigfoot	"});
good.push({name:"Bikkuriman World - Gekitou Sei Senshi	"});
good.push({name:"Bill & Ted's Excellent Video Game Adventure	"});
good.push({name:"Bill Elliott's NASCAR Challenge	"});
good.push({name:"Binary Land	"});
good.push({name:"Bing Kuang Ji Dan Zi - Flighty Chicken	"});
good.push({name:"Bingo	"});
good.push({name:"Bio Hazard	"});
good.push({name:"Bio Miracle Bokutte Upa	"});
good.push({name:"Bionic Commando	"});
good.push({name:"Bird Week	"});
good.push({name:"Black Bass USA, The	"});
good.push({name:"Black Bass, The	"});
good.push({name:"Blackjack	"});
good.push({name:"Blades of Steel	"});
good.push({name:"Blaster Master	"});
good.push({name:"Blodia Land - Puzzle Quest	"});
good.push({name:"Bloody Warriors - Shan-Go no Gyakushuu	"});
good.push({name:"Blue Marlin, The	"});
good.push({name:"Blues Brothers, The	"});
good.push({name:"Bo Jackson Baseball	"});
good.push({name:"Bokosuka Wars	"});
good.push({name:"Boku Koku Shuu Kin	"});
good.push({name:"Bomberman	"});
good.push({name:"Bomberman II	"});
good.push({name:"Bonk's Adventure	"});
good.push({name:"Bonza	"});
good.push({name:"Booby Kids	"});
good.push({name:"Boogerman (Pirate)	"});
good.push({name:"Boulder Dash	"});
good.push({name:"Boy and His Blob, A - Trouble on Blobolonia	"});
good.push({name:"Bram Stoker's Dracula	"});
good.push({name:"Break Time - The National Pool Tour	"});
good.push({name:"BreakThru	"});
good.push({name:"Brush Roller	"});
good.push({name:"Bubble Bath Babes	"});
good.push({name:"Bubble Bobble	"});
good.push({name:"Bubble Bobble Part 2	"});
good.push({name:"Bucky O'Hare	"});
good.push({name:"Bugs Bunny Birthday Blowout, The	"});
good.push({name:"Bugs Bunny Crazy Castle, The	"});
good.push({name:"Bump'n'Jump	"});
good.push({name:"Burai Fighter	"});
good.push({name:"BurgerTime	"});
good.push({name:"Business Wars	"});
good.push({name:"Buzz and Waldog	"});
good.push({name:"B-Wings	"});
good.push({name:"Cabal	"});
good.push({name:"Cadillac	"});
good.push({name:"Caesars Palace	"});
good.push({name:"California Games	"});
good.push({name:"California Raisins, The - The Grape Escape	"});
good.push({name:"Captain America and The Avengers	"});
good.push({name:"Captain Ed	"});
good.push({name:"Captain Planet and The Planeteers	"});
good.push({name:"Captain Silver	"});
good.push({name:"Captain SkyHawk	"});
good.push({name:"Captain Tsubasa Vol. II - Super Striker	"});
good.push({name:"Casino Derby	"});
good.push({name:"Casino Kid	"});
good.push({name:"Casino Kid 2	"});
good.push({name:"Castelian	"});
good.push({name:"Castle of Deceit	"});
good.push({name:"Castle of Dragon	"});
good.push({name:"Castle Quest	"});
good.push({name:"Castlequest	"});
good.push({name:"Castlevania	"});
good.push({name:"Castlevania II - Simon's Quest	"});
good.push({name:"Castlevania III - Dracula's Curse	"});
good.push({name:"Caveman Games	"});
good.push({name:"Chack 'n Pop	"});
good.push({name:"Challenge of the Dragon	"});
good.push({name:"Challenger	"});
good.push({name:"Championship Bowling	"});
good.push({name:"Championship Lode Runner	"});
good.push({name:"Championship Pool	"});
good.push({name:"Championship Rally	"});
good.push({name:"Chaos World	"});
good.push({name:"Cheetah Men II	"});
good.push({name:"Chess Academys	"});
good.push({name:"Chessmaster, The	"});
good.push({name:"Chester Field - Ankoku Shin heno Chousen	"});
good.push({name:"Chibi Maruko-Chan - Uki Uki Shopping	"});
good.push({name:"Chiisana Obake - Acchi Socchi Kocchi	"});
good.push({name:"Chik Bik Ji Jin - Saam Gwok Ji	"});
good.push({name:"Chiller	"});
good.push({name:"Chinese Checkers	"});
good.push({name:"Chinese Kungfu	"});
good.push({name:"Chip 'n Dale Rescue Rangers	"});
good.push({name:"Chip 'n Dale Rescue Rangers 2	"});
good.push({name:"Chiyonofuji no Ooichou	"});
good.push({name:"Choplifter	"});
good.push({name:"Choujikuu Yousai - Macross	"});
good.push({name:"Choujin Sentai - Jetman	"});
good.push({name:"Chu Da D	"});
good.push({name:"Chu Han Zheng Ba - The War Between Chu & Han	"});
good.push({name:"Chu Liu Xiang	"});
good.push({name:"Chubby Cherub	"});
good.push({name:"Chuugoku Janshi Story - Tonpuu	"});
good.push({name:"Chuugoku Senseijutsu	"});
good.push({name:"Chuugoku Taitei	"});
good.push({name:"Chuuka Taisen	"});
good.push({name:"Circus Caper	"});
good.push({name:"Circus Charlie	"});
good.push({name:"City Adventure Touch - Mystery of Triangle	"});
good.push({name:"City Connection	"});
good.push({name:"Clash at Demonhead	"});
good.push({name:"Classic Concentration	"});
good.push({name:"Cliffhanger	"});
good.push({name:"Clu Clu Land	"});
good.push({name:"Clu Clu Land D	"});
good.push({name:"Cobra Command	"});
good.push({name:"Cobra Mission (CN-27)	"});
good.push({name:"Cobra Triangle	"});
good.push({name:"Cocoron	"});
good.push({name:"Code Name - Viper	"});
good.push({name:"Color A Dinosaur	"});
good.push({name:"Columbus - Ougon no Yoake	"});
good.push({name:"Commando	"});
good.push({name:"Commandos	"});
good.push({name:"Conan - The Mysteries of Time	"});
good.push({name:"Conflict	"});
good.push({name:"Conquest of the Crystal Palace	"});
good.push({name:"Contra	"});
good.push({name:"Contra Force	"});
good.push({name:"Contra Spirits (Pirate)	"});
good.push({name:"Cool World	"});
good.push({name:"Cosmic Epsilon	"});
good.push({name:"Cosmic Wars	"});
good.push({name:"Cosmo Police Galivan	"});
good.push({name:"Cosmos Cop (CN-08)	"});
good.push({name:"Cowboy Kid	"});
good.push({name:"Crackout	"});
good.push({name:"Crash 'n the Boys - Street Challenge	"});
good.push({name:"Crayon Shin-Chan	"});
good.push({name:"Crayon Shin-Chan - Ora to Poi Poi	"});
good.push({name:"Crazy Climber	"});
good.push({name:"Creatom	"});
good.push({name:"Crime Busters	"});
good.push({name:"Crisis Force	"});
good.push({name:"Cross Fire	"});
good.push({name:"Crystal Mines	"});
good.push({name:"Crystalis	"});
good.push({name:"Cvetnye Linii	"});
good.push({name:"Cyberball	"});
good.push({name:"Cybernoid - The Fighting Machine	"});
good.push({name:"Cycle Race - Road Man	"});
good.push({name:"D.J. Boy	"});
good.push({name:"Da Hua Xi You	"});
good.push({name:"Dai Meiro - Meikyuu no Tatsujin	"});
good.push({name:"Dai-2-Ji - Super Robot Taisen	"});
good.push({name:"Daikaijuu Deburas	"});
good.push({name:"Daiku no Gen San 2 - Akage no Dan no Gyakushuu	"});
good.push({name:"Daisenryaku	"});
good.push({name:"Daiva - Imperial of Nirsartia	"});
good.push({name:"Dance Aerobics	"});
good.push({name:"Dance Xtreme - Prima	"});
good.push({name:"Dancing Blocks	"});
good.push({name:"Danny Sullivan's Indy Heat	"});
good.push({name:"Dark Lord	"});
good.push({name:"Darkman	"});
good.push({name:"Darkseed	"});
good.push({name:"Darkwing Duck	"});
good.push({name:"Dash Galaxy in the Alien Asylum	"});
good.push({name:"Datach - Battle Rush - Build Up Robot Tournament	"});
good.push({name:"Datach - Dragon Ball Z - Gekitou Tenkaichi Budou Kai	"});
good.push({name:"Datach - J League Super Top Players	"});
good.push({name:"Datach - SD Gundam - Gundam Wars	"});
good.push({name:"Datach - Ultraman Club - Supokon Fight!	"});
good.push({name:"Datach - Yuu Yuu Hakusho - Bakutou Ankoku Bujutsu Kai	"});
good.push({name:"Day Dreamin' Davey	"});
good.push({name:"Days of Thunder	"});
good.push({name:"Deadly Towers	"});
good.push({name:"Death Race	"});
good.push({name:"Deathbots	"});
good.push({name:"Deblock	"});
good.push({name:"Decathlon	"});
good.push({name:"Deep Dungeon 4 - Kuro no Youjutsushi	"});
good.push({name:"Deep Dungeon III - Yuushi heno Tabi	"});
good.push({name:"Defender II	"});
good.push({name:"Defender of the Crown	"});
good.push({name:"Defenders of Dynatron City	"});
good.push({name:"Deja Vu	"});
good.push({name:"Demo Boy 2	"});
good.push({name:"Demogorgon Monk	"});
good.push({name:"Demon Sword	"});
good.push({name:"Derby Stallion - Zenkoku Han	"});
good.push({name:"Desert Commander	"});
good.push({name:"Destination Earthstar	"});
good.push({name:"Destiny of an Emperor	"});
good.push({name:"Devil Man	"});
good.push({name:"Devil World	"});
good.push({name:"Dezaemon	"});
good.push({name:"Di Dao Zhan	"});
good.push({name:"Diablo (NJ037)	"});
good.push({name:"Dian Shi Ma Li	"});
good.push({name:"Dick Tracy	"});
good.push({name:"Die Hard	"});
good.push({name:"Dig Dug	"});
good.push({name:"Dig Dug II - Trouble in Paradise	"});
good.push({name:"Digger - The Legend of the Lost City	"});
good.push({name:"Digital Devil Monogatari - Megami Tensei	"});
good.push({name:"Digital Devil Monogatari - Megami Tensei II	"});
good.push({name:"Digital Dragon	"});
good.push({name:"Dirty Harry - The War Against Drugs	"});
good.push({name:"Dizzy The Adventurer	"});
good.push({name:"Doctor PC Jr. - Xue Si Dian Nao	"});
good.push({name:"Dokuganryuu Masamune	"});
good.push({name:"Don Doko Don	"});
good.push({name:"Don Doko Don 2	"});
good.push({name:"Donald Land	"});
good.push({name:"Dong Dong Nao II - Guo Zhong Ying Wen (Middle School English II)	"});
good.push({name:"Donkey Kong	"});
good.push({name:"Donkey Kong 3	"});
good.push({name:"Donkey Kong Classics	"});
good.push({name:"Donkey Kong Country 4 (Pirate)	"});
good.push({name:"Donkey Kong Jr.	"});
good.push({name:"Donkey Kong Jr. Math	"});
good.push({name:"Door Door	"});
good.push({name:"Doraemon	"});
good.push({name:"Doraemon - Giga Zombie no Gyakushuu	"});
good.push({name:"Double Dare	"});
good.push({name:"Double Dragon	"});
good.push({name:"Double Dragon II - The Revenge	"});
good.push({name:"Double Dragon III - The Sacred Stones	"});
good.push({name:"Double Dribble	"});
good.push({name:"Double Moon Densetsu	"});
good.push({name:"Double Strike	"});
good.push({name:"Dough Boy	"});
good.push({name:"Downtown - Nekketsu Koushin Kyoku - Soreyuke Daiundoukai	"});
good.push({name:"Downtown Special - Kunio-kun no Jidaigeki Dayo Zenin Shuugou!	"});
good.push({name:"Dr. Chaos	"});
good.push({name:"Dr. Jekyll and Mr. Hyde	"});
good.push({name:"Dr. Mario	"});
good.push({name:"Drac's Night Out	"});
good.push({name:"Dragon Ball - Dai Maou Fukkatsu	"});
good.push({name:"Dragon Ball 3 - Gokuu Den	"});
good.push({name:"Dragon Ball Z - Kyoushuu! Saiya Jin	"});
good.push({name:"Dragon Ball Z - Super Butouden 2 (Pirate)	"});
good.push({name:"Dragon Ball Z Gaiden - Saiya Jin Zetsumetsu Keikaku	"});
good.push({name:"Dragon Ball Z II - Gekishin Freeza!!	"});
good.push({name:"Dragon Ball Z III - Ressen Jinzou Ningen	"});
good.push({name:"Dragon Ball Z IV (Pirate)	"});
good.push({name:"Dragon Ball Z V (Pirate)	"});
good.push({name:"Dragon Buster	"});
good.push({name:"Dragon Buster II - Yami no Fuuin	"});
good.push({name:"Dragon Fighter	"});
good.push({name:"Dragon Power	"});
good.push({name:"Dragon Quest VIII	"});
good.push({name:"Dragon Scroll - Yomigaerishi Maryuu	"});
good.push({name:"Dragon Spirit - The New Legend	"});
good.push({name:"Dragon Warrior	"});
good.push({name:"Dragon Warrior II	"});
good.push({name:"Dragon Warrior III	"});
good.push({name:"Dragon Warrior IV	"});
good.push({name:"Dragon Wars	"});
good.push({name:"Dragon, The (Pirate)	"});
good.push({name:"Dragon's Lair	"});
good.push({name:"Dream Master	"});
good.push({name:"Drop Zone	"});
good.push({name:"Duck	"});
good.push({name:"Duck Hunt	"});
good.push({name:"Duck Tales	"});
good.push({name:"Duck Tales 2	"});
good.push({name:"Dudes With Attitude	"});
good.push({name:"Dungeon Kid	"});
good.push({name:"Dungeon Magic - Sword of the Elements	"});
good.push({name:"Duo Bao Xiao Ying Hao - Guang Ming yu An Hei Chuan Shuo	"});
good.push({name:"Dusty Diamond's All-Star Softball	"});
good.push({name:"Dynamite Bowl	"});
good.push({name:"Dynowarz - The Destruction of Spondylus	"});
good.push({name:"Earthbound	"});
good.push({name:"EarthWorm Jim 2 (Pirate)	"});
good.push({name:"EarthWorm Jim 3 (Pirate)	"});
good.push({name:"Educational Computer 2000	"});
good.push({name:"Eggland - Meikyuu no Fukkatsu	"});
good.push({name:"Egypt	"});
good.push({name:"El Monstruo de Los Globos	"});
good.push({name:"Elevator Action	"});
good.push({name:"Eliminator Boat Duel	"});
good.push({name:"Elite	"});
good.push({name:"Elysion	"});
good.push({name:"Emoyan no 10 Bai Pro Yakyuu	"});
good.push({name:"English Word Blaster V1.0	"});
good.push({name:"Erika to Satoru no Yume Bouken	"});
good.push({name:"Erunaaku no Zaihou	"});
good.push({name:"Escape From Atlantis, The	"});
good.push({name:"Esper Bouken Tai	"});
good.push({name:"Esper Dream 2 - Aratanaru Tatakai	"});
good.push({name:"Europe Sensen	"});
good.push({name:"EverQuest	"});
good.push({name:"Excitebike	"});
good.push({name:"Exciting Boxing	"});
good.push({name:"Exed Exes	"});
good.push({name:"Exerion	"});
good.push({name:"Exodus - Journey to the Promised Land	"});
good.push({name:"F1 Circus	"});
good.push({name:"F-1 Race	"});
good.push({name:"F-117A Stealth Fighter	"});
good.push({name:"F-15 City War	"});
good.push({name:"F-15 Strike Eagle	"});
good.push({name:"Facemaker	"});
good.push({name:"Famicom Disk System BIOS	"});
good.push({name:"Famicom Doubutsu Seitai Zukan! - Katte ni Shirokuma - Mori wo Sukue no Maki!	"});
good.push({name:"Famicom Igo Nyuumon	"});
good.push({name:"Famicom Jump - Eiyuu Retsuden	"});
good.push({name:"Famicom Jump II - Saikyou no 7 Nin	"});
good.push({name:"Famicom Meijin Sen	"});
good.push({name:"Famicom Shougi - Ryuuousen	"});
good.push({name:"Famicom Top Management	"});
good.push({name:"Famicom Wars	"});
good.push({name:"Famicom Yakyuu Han	"});
good.push({name:"Family BASIC	"});
good.push({name:"Family Circuit	"});
good.push({name:"Family Circuit '91	"});
good.push({name:"Family Feud	"});
good.push({name:"Family Jockey	"});
good.push({name:"Family Mahjong	"});
good.push({name:"Family Mahjong II - Shanghai heno Michi	"});
good.push({name:"Family Quiz	"});
good.push({name:"Family School	"});
good.push({name:"Family Tennis	"});
good.push({name:"Family Trainer - Fuuun!! Takeshi Jou 2	"});
good.push({name:"Family Trainer - Jogging Race	"});
good.push({name:"Family Trainer - Meiro Daisakusen	"});
good.push({name:"Family Trainer - Rairai Kyonsees	"});
good.push({name:"Family Trainer - Totsugeki! Fuuun Takeshi-jou	"});
good.push({name:"Famista '89 - Kaimaku Han!!	"});
good.push({name:"Famista '90	"});
good.push({name:"Famista '91	"});
good.push({name:"Famista '92	"});
good.push({name:"Famista '93	"});
good.push({name:"Famista '94	"});
good.push({name:"Fan Kong Jing Ying	"});
good.push({name:"Fantastic Adventures of Dizzy, The	"});
good.push({name:"Fantasy Zone	"});
good.push({name:"Fantasy Zone 2 - The Teardrop of Opa-Opa	"});
good.push({name:"Faria - A World of Mystery & Danger!	"});
good.push({name:"Fatal Fury 2 (Pirate)	"});
good.push({name:"Faxanadu	"});
good.push({name:"Felix the Cat	"});
good.push({name:"Feng Yin Dao (NJ072)	"});
good.push({name:"Ferrari - Grand Prix Challenge	"});
good.push({name:"Fester's Quest	"});
good.push({name:"Field Combat	"});
good.push({name:"FIFA 97 International Soccer	"});
good.push({name:"FIFA International 2' 96	"});
good.push({name:"Fighting Hero	"});
good.push({name:"Fighting Hero III	"});
good.push({name:"Fighting Road	"});
good.push({name:"Final Combat	"});
good.push({name:"Final Fantasy	"});
good.push({name:"Final Fantasy I & II	"});
good.push({name:"Final Fantasy II	"});
good.push({name:"Final Fantasy III	"});
good.push({name:"Final Fantasy V	"});
good.push({name:"Final Fantasy VII (NJ063)	"});
good.push({name:"Final Fight 3	"});
good.push({name:"Final Lap	"});
good.push({name:"Fire Dragon	"});
good.push({name:"Fire Emblem	"});
good.push({name:"Fire Emblem Gaiden	"});
good.push({name:"Fire Hawk	"});
good.push({name:"Fire 'n Ice	"});
good.push({name:"Firehouse Rescue	"});
good.push({name:"Fist of the North Star	"});
good.push({name:"Flappy	"});
good.push({name:"Fleet Commander	"});
good.push({name:"Flight of the Intruder	"});
good.push({name:"Flintstones, The - The Rescue of Dino & Hoppy	"});
good.push({name:"Flintstones, The - The Surprise at Dinosaur Peak!	"});
good.push({name:"Flipull - An Exciting Cube Game	"});
good.push({name:"Flying Dragon - The Secret Scroll	"});
good.push({name:"Flying Hero	"});
good.push({name:"Flying Warriors	"});
good.push({name:"Fong Shen Bang - Zhu Lu Zhi Zhan	"});
good.push({name:"Forcity	"});
good.push({name:"Formation Z	"});
good.push({name:"Formula 1 Sensation	"});
good.push({name:"Formula One - Built To Win	"});
good.push({name:"Foton - The Ultimate Game on Planet Earth	"});
good.push({name:"Frankenstein - The Monster Returns	"});
good.push({name:"Freedom Force	"});
good.push({name:"Friday the 13th	"});
good.push({name:"Front Line	"});
good.push({name:"Fun Blaster Pak	"});
good.push({name:"Fun House	"});
good.push({name:"Fushigi no Umi no Nadia	"});
good.push({name:"Fuzzical Fighter	"});
good.push({name:"G.I. Joe	"});
good.push({name:"G.I. Joe - The Atlantis Factor	"});
good.push({name:"Gaiapolis	"});
good.push({name:"Galactic Crusader	"});
good.push({name:"Galaga - Demons of Death	"});
good.push({name:"Galaxian	"});
good.push({name:"Galaxy 5000	"});
good.push({name:"Gambler Jiko Chuushin Ha - Mahjong Game	"});
good.push({name:"Gambler Jiko Chuushin Ha 2	"});
good.push({name:"Game Genie	"});
good.push({name:"Game Party	"});
good.push({name:"Ganbare Goemon 2	"});
good.push({name:"Ganbare Goemon Gaiden - Kieta Ougon Kiseru	"});
good.push({name:"Ganbare Goemon Gaiden 2 - Tenka no Zaihou	"});
good.push({name:"Ganbare Goemon! - Karakuri Douchuu	"});
good.push({name:"Ganbare Pennant Race!	"});
good.push({name:"Ganso Saiyuuki - Super Monkey Daibouken	"});
good.push({name:"Garfield - A Week of Garfield	"});
good.push({name:"Gargoyle's Quest II - The Demon Darkness	"});
good.push({name:"Garou Densetsu Special	"});
good.push({name:"Gauntlet	"});
good.push({name:"Gauntlet II	"});
good.push({name:"Ge Ge Ge no Kitarou 2 - Youkai Gundan no Chousen	"});
good.push({name:"Geimos	"});
good.push({name:"Gekitotsu Yonku Battle	"});
good.push({name:"Gemfire	"});
good.push({name:"Genghis Khan	"});
good.push({name:"Genpei Touma Den - Computer Boardgame	"});
good.push({name:"George Foreman's KO Boxing	"});
good.push({name:"Getsufuu Maden	"});
good.push({name:"Ghostbusters	"});
good.push({name:"Ghostbusters II	"});
good.push({name:"Ghosts 'N Goblins	"});
good.push({name:"Ghoul School	"});
good.push({name:"Gimmi a Break - Shijou Saikyou no Quiz Ou Ketteisen	"});
good.push({name:"Gimmi a Break - Shijou Saikyou no Quiz Ou Ketteisen 2	"});
good.push({name:"Ginga Eiyuu Densetsu	"});
good.push({name:"Ginga no Sannin	"});
good.push({name:"GLK Dance by FengLi	"});
good.push({name:"Go! Benny!	"});
good.push({name:"Goal!	"});
good.push({name:"Goal! Two	"});
good.push({name:"Godzilla - Monster of Monsters!	"});
good.push({name:"Godzilla 2 - War of the Monsters	"});
good.push({name:"Gold Medal Challenge '92	"});
good.push({name:"Golden KTV	"});
good.push({name:"Golf	"});
good.push({name:"Golf '92, The	"});
good.push({name:"Golf Club - Birdy Rush	"});
good.push({name:"Golf Grand Slam	"});
good.push({name:"Golf Ko Open	"});
good.push({name:"Golgo 13 - Top Secret Episode	"});
good.push({name:"Gomoku Narabe	"});
good.push({name:"Goonies II, The	"});
good.push({name:"Goonies, The	"});
good.push({name:"Gorby no Pipeline Daisakusen	"});
good.push({name:"Gorilla Man, The	"});
good.push({name:"Gotcha! - The Sport!	"});
good.push({name:"Gozonji - Yaji Kita Chin Douchuu	"});
good.push({name:"Gradius	"});
good.push({name:"Gradius II	"});
good.push({name:"Grand Master	"});
good.push({name:"Great Battle Cyber	"});
good.push({name:"Great Deal	"});
good.push({name:"Great Waldo Search, The	"});
good.push({name:"Great Wall, The	"});
good.push({name:"Greg Norman's Golf Power	"});
good.push({name:"Gremlins 2 - The New Batch	"});
good.push({name:"Gu Mu Li Ying	"});
good.push({name:"Guardian Legend, The	"});
good.push({name:"Guerrilla War	"});
good.push({name:"Gumshoe	"});
good.push({name:"Gun Hed	"});
good.push({name:"Gun.Smoke	"});
good.push({name:"Gun-Nac	"});
good.push({name:"Gyrodine	"});
good.push({name:"Gyromite	"});
good.push({name:"Gyruss	"});
good.push({name:"Hacker, The	"});
good.push({name:"Haja no Fuuin	"});
good.push({name:"Hammerin' Harry	"});
good.push({name:"Hana no Star Kaidou	"});
good.push({name:"Hanafuda Yuukyou Den - Nagarebana Oryuu	"});
good.push({name:"Hanjuku Eiyuu	"});
good.push({name:"Happy Pairs	"});
good.push({name:"Harlem Globetrotters	"});
good.push({name:"Harry Story	"});
good.push({name:"Harry's Legend (Pirate)	"});
good.push({name:"Harvest Moon	"});
good.push({name:"Hatris	"});
good.push({name:"Hayauchi Super Igo	"});
good.push({name:"He Xin Wei Ji	"});
good.push({name:"Heavy Barrel	"});
good.push({name:"Heavy Shreddin'	"});
good.push({name:"Heisei Tensai Bakabon	"});
good.push({name:"Hell Fighter	"});
good.push({name:"Hello Kitty no Ohanabatake	"});
good.push({name:"Hello Kitty World	"});
good.push({name:"Herakles no Eikou - Toujin Makyou Den	"});
good.push({name:"Herakles no Eikou 2 - Titan no Metsubou	"});
good.push({name:"Hero on Devil Lands	"});
good.push({name:"Hero Quest	"});
good.push({name:"High Speed	"});
good.push({name:"Hinotori - Houou Hen - Gaou no Bouken	"});
good.push({name:"Hirake! Ponkikki	"});
good.push({name:"Hiryuu no Ken II - Dragon no Tsubasa	"});
good.push({name:"Hiryuu no Ken Special - Fighting Wars	"});
good.push({name:"Hissatsu Doujou Yaburi	"});
good.push({name:"Hissatsu Shigoto Nin	"});
good.push({name:"Hit Marmot	"});
good.push({name:"Hit the Ice	"});
good.push({name:"Hogan's Alley	"});
good.push({name:"Hokkaidou Rensa Satsujin - Okhotsk ni Kiyu	"});
good.push({name:"Hokuto no Ken	"});
good.push({name:"Hokuto no Ken 3 - Shin Seiki Souzou Seiken Restuden	"});
good.push({name:"Hokuto no Ken 4 - Shichisei Haken Den - Hokuto Shinken no Kanata he	"});
good.push({name:"Hollywood Squares	"});
good.push({name:"Holy Diver	"});
good.push({name:"Home Alone	"});
good.push({name:"Home Alone 2 - Lost in New York	"});
good.push({name:"Home Run Nighter - Pennant League!!	"});
good.push({name:"Home Run Nighter '90 - The Pennant League	"});
good.push({name:"Hon Shougi - Naitou 9 Dan Shougi Hiden	"});
good.push({name:"Honoo no Doukyuuji - Dodge Danpei	"});
good.push({name:"Honoo no Doukyuuji - Dodge Danpei 2	"});
good.push({name:"Hook	"});
good.push({name:"Hoops	"});
good.push({name:"Hoshi wo Miru Hito	"});
good.push({name:"Hot Dance 2000	"});
good.push({name:"Hot Slot	"});
good.push({name:"Hototogisu	"});
good.push({name:"Hottaaman no Chitei Tanken	"});
good.push({name:"Hu Lu Jin Gang (NJ039)	"});
good.push({name:"Huan Shi Lu (NJ034)	"});
good.push({name:"Huang Di	"});
good.push({name:"Huang Jin Tai Yang	"});
good.push({name:"Hudson Hawk	"});
good.push({name:"Hudson's Adventure Island	"});
good.push({name:"Hudson's Adventure Island II	"});
good.push({name:"Hudson's Adventure Island III	"});
good.push({name:"Huge Insect	"});
good.push({name:"Hunt for Red October, The	"});
good.push({name:"HVC Kensa Cassette Contlorer Test (Sample)	"});
good.push({name:"Hyakkiyakou	"});
good.push({name:"Hyaku no Sekai no Monogatari - The Tales on a Watery Wilderness	"});
good.push({name:"Hydlide	"});
good.push({name:"Hydlide 3 - Yami Kara no Houmonsha	"});
good.push({name:"Hyokkori Hyoutan Shima - Nazo no Kaizokusen	"});
good.push({name:"Hyper Sports	"});
good.push({name:"I Can Remember	"});
good.push({name:"I Love Softball	"});
good.push({name:"Ice Climber	"});
good.push({name:"Ice Hockey	"});
good.push({name:"Ide Yousuke Meijin no Jissen Mahjong	"});
good.push({name:"Ide Yousuke Meijin no Jissen Mahjong 2	"});
good.push({name:"Idol Hakkenden	"});
good.push({name:"Igo - Kyuu Roban Taikyoku	"});
good.push({name:"Igo Meikan	"});
good.push({name:"Igo Shinan	"});
good.push({name:"Igo Shinan '91	"});
good.push({name:"Igo Shinan '92	"});
good.push({name:"Igo Shinan '93	"});
good.push({name:"Igo Shinan '94	"});
good.push({name:"Ikari III - The Rescue	"});
good.push({name:"Ikari Warriors	"});
good.push({name:"Ikari Warriors II - Victory Road	"});
good.push({name:"Ike Ike! Nekketsu Hockey Bu - Subette Koronde Dai Rantou	"});
good.push({name:"Ikinari Musician	"});
good.push({name:"Ikki	"});
good.push({name:"Image Fight	"});
good.push({name:"Immortal, The	"});
good.push({name:"Impossible Mission II	"});
good.push({name:"Incredible Crash Dummies, The	"});
good.push({name:"Indiana Jones and the Last Crusade	"});
good.push({name:"Indiana Jones and the Temple of Doom	"});
good.push({name:"Indora no Hikari	"});
good.push({name:"Infiltrator	"});
good.push({name:"Insector X	"});
good.push({name:"International Cricket	"});
good.push({name:"Iron Tank - The Invasion of Normandy	"});
good.push({name:"Ironsword - Wizards & Warriors II	"});
good.push({name:"Isaki Shuugorou no Keiba Hisshou Gaku	"});
good.push({name:"Ishin no Arashi	"});
good.push({name:"Isolated Warrior	"});
good.push({name:"Itadaki Street - Watashi no Mise ni Yottette	"});
good.push({name:"Ivan Ironman Stewart's Super Off-Road	"});
good.push({name:"Jack Nicklaus' Greatest 18 Holes of Major Championship Golf	"});
good.push({name:"Jackal	"});
good.push({name:"Jackie Chan's Action Kung Fu	"});
good.push({name:"Jajamaru Gekimaden - Maboroshi no Kinmajou	"});
good.push({name:"Jajamaru no Daibouken	"});
good.push({name:"James Bond Jr	"});
good.push({name:"Jangou	"});
good.push({name:"Jarinko Chie - Bakudan Musume no Shiawase Sagashi	"});
good.push({name:"Jaws	"});
good.push({name:"Jeopardy!	"});
good.push({name:"Jesus - Kyoufu no Bio Monster	"});
good.push({name:"Jetsons, The - Cogswell's Caper!	"});
good.push({name:"Ji Du Shan En Chou Ji - Le Comte de Monte-Cristo	"});
good.push({name:"Jia A Fung Yun	"});
good.push({name:"Jikuu Yuuden - Debias	"});
good.push({name:"Jim Henson's Muppet Adventure - Chaos at the Carnival	"});
good.push({name:"Jimmy Connor's Tennis	"});
good.push({name:"Jin Gwok Sei Chuen Saang	"});
good.push({name:"Jin Yong Qun Xia Zhuan - Shu Jian Jiang Shan (NJ031)	"});
good.push({name:"Jing Ke Xin Zhuan	"});
good.push({name:"J-League Fighting Soccer - The King of Ace Strikers	"});
good.push({name:"J-League Winning Goal	"});
good.push({name:"Joe & Mac - Caveman Ninja	"});
good.push({name:"John Elway's Quarterback	"});
good.push({name:"Jongbou	"});
good.push({name:"Jordan Vs Bird - One On One	"});
good.push({name:"Joshua	"});
good.push({name:"Journey to Silius	"});
good.push({name:"Journey to the West	"});
good.push({name:"Joust	"});
good.push({name:"Jovial Race	"});
good.push({name:"Joy Mech Fight	"});
good.push({name:"Joypad Test Cartridge	"});
good.push({name:"Jue Dai Ying Xiong	"});
good.push({name:"Jumbo Ozaki no Hole in One Professional	"});
good.push({name:"Jumpin' Kid - Jack to Mame no Ki Monogatari	"});
good.push({name:"Jungle Book, The	"});
good.push({name:"Jurassic Boy 2	"});
good.push({name:"Jurassic Park	"});
good.push({name:"Just Breed	"});
good.push({name:"Juuouki	"});
good.push({name:"Juvei Quest	"});
good.push({name:"Kabuki - Quantum Fighter	"});
good.push({name:"Kabushiki Doujou	"});
good.push({name:"Kaettekita! Gunjin Shougi - Nanya Sore!	"});
good.push({name:"Kagerou Densetsu	"});
good.push({name:"Kaguya Hime Densetsu	"});
good.push({name:"Kaijuu Monogatari	"});
good.push({name:"Kaiketsu Yanchamaru 2 - Karakuri Land	"});
good.push({name:"Kaiketsu Yanchamaru 3 - Taiketsu! Zouringen	"});
good.push({name:"Kamen no Ninja - Akakage	"});
good.push({name:"Kamen no Ninja - Hanamaru	"});
good.push({name:"Kamen Rider Club - Gekitotsu Shocker Land	"});
good.push({name:"Kamen Rider SD - Granshocker no Yabou	"});
good.push({name:"Kanshakudama Nage Kantarou no Toukaidou Gojuusan Tsugi	"});
good.push({name:"Karakuri Kengou Den - Musashi Road - Karakuri Nin Hashiru!	"});
good.push({name:"Karaoke Studio	"});
good.push({name:"Karate Champ	"});
good.push({name:"Karate Kid, The	"});
good.push({name:"Karateka	"});
good.push({name:"Karnov	"});
good.push({name:"Kart Fighter (Pirate)	"});
good.push({name:"Kawa no Nushi Tsuri	"});
good.push({name:"Keiba Simulation - Honmei	"});
good.push({name:"Kero Kero Keroppi no Daibouken	"});
good.push({name:"Kero Kero Keroppi no Daibouken 2 - Donuts Ike ha Oosawagi!	"});
good.push({name:"Keroppi to Keroriinu no Splash Bomb!	"});
good.push({name:"Kibord 003	"});
good.push({name:"Kick Master	"});
good.push({name:"Kick Off	"});
good.push({name:"Kickle Cubicle	"});
good.push({name:"Kid Icarus	"});
good.push({name:"Kid Klown	"});
good.push({name:"Kid Kool and the Quest for the 7 Wonder Herbs	"});
good.push({name:"Kid Niki - Radical Ninja	"});
good.push({name:"King Kong 2 - Ikari no Megaton Punch	"});
good.push({name:"King Neptune's Adventure	"});
good.push({name:"King of Fighters 96, The (Pirate)	"});
good.push({name:"King of Fighters 97, The (Pirate)	"});
good.push({name:"King of Fighters 99, The (Pirate)	"});
good.push({name:"King of Kings	"});
good.push({name:"King of Kings - Early Years, The	"});
good.push({name:"King's Knight	"});
good.push({name:"Kings of the Beach	"});
good.push({name:"King's Quest V	"});
good.push({name:"Kirby's Adventure	"});
good.push({name:"Kiteretsu Dai Hyakka	"});
good.push({name:"Kiwi Kraze - A Bird-Brained Adventure!	"});
good.push({name:"Klash Ball	"});
good.push({name:"Klax	"});
good.push({name:"Knight Rider	"});
good.push({name:"Konami Hyper Soccer	"});
good.push({name:"Korean Igo	"});
good.push({name:"Kou Dai Bao Shi - Yin	"});
good.push({name:"Kouryuu Densetsu Villgust Gaiden	"});
good.push({name:"Koushien	"});
good.push({name:"Krazy Kreatures	"});
good.push({name:"Krion Conquest, The	"});
good.push({name:"Krusty's Fun House	"});
good.push({name:"Kujaku Ou	"});
good.push({name:"Kujaku Ou 2	"});
good.push({name:"Kung Fu	"});
good.push({name:"Kung-Fu Heroes	"});
good.push({name:"Kunio-kun no Nekketsu Soccer League	"});
good.push({name:"Kurogane Hiroshi no Yosou Daisuki! - Kachiuma Densetsu	"});
good.push({name:"Kyatto Ninden Teyandee	"});
good.push({name:"Kyonshiizu 2	"});
good.push({name:"Kyouryuu Sentai Juuranger	"});
good.push({name:"Kyuukyoku Harikiri Koushien	"});
good.push({name:"Kyuukyoku Harikiri Stadium	"});
good.push({name:"Kyuukyoku Harikiri Stadium - Heisei Gannen Han	"});
good.push({name:"Kyuukyoku Harikiri Stadium 3	"});
good.push({name:"Labyrinth	"});
good.push({name:"Ladies Golf	"});
good.push({name:"Lagrange Point	"});
good.push({name:"Laser Invasion	"});
good.push({name:"Last Action Hero	"});
good.push({name:"Last Armageddon	"});
good.push({name:"Last Ninja, The	"});
good.push({name:"Last Starfighter, The	"});
good.push({name:"Law of the West	"});
good.push({name:"Layla	"});
good.push({name:"Lee Trevino's Fighting Golf	"});
good.push({name:"Legacy of the Wizard	"});
good.push({name:"Legend of Kage, The	"});
good.push({name:"Legend of Prince Valiant, The	"});
good.push({name:"Legend of Robin Hood, The	"});
good.push({name:"Legend of the Ghost Lion	"});
good.push({name:"Legend of Zelda, The	"});
good.push({name:"Legendary Wings	"});
good.push({name:"Legends of the Diamond - The Baseball Championship Game	"});
good.push({name:"Lei Dian Huang Bi Ka Qiu Chuan Shuo (NJ046)	"});
good.push({name:"Lemmings	"});
good.push({name:"L'Empereur	"});
good.push({name:"Lethal Weapon	"});
good.push({name:"Liang Shan Ying Xiong (NJ023)	"});
good.push({name:"Life Force	"});
good.push({name:"Lin Ze Xu Jin Yan	"});
good.push({name:"Linus Spacehead's Cosmic Crusade	"});
good.push({name:"Lion King III, The Simon and Pumba (Pirate)	"});
good.push({name:"Lion King, The	"});
good.push({name:"Lion King, The (1995) (Pirate)	"});
good.push({name:"Lipple Island	"});
good.push({name:"Little League Baseball - Championship Series	"});
good.push({name:"Little Magic	"});
good.push({name:"Little Mermaid, The	"});
good.push({name:"Little Nemo - The Dream Master	"});
good.push({name:"Little Ninja Brothers	"});
good.push({name:"Little Red Hood	"});
good.push({name:"Little Samson	"});
good.push({name:"Locksmith	"});
good.push({name:"Lode Runner	"});
good.push({name:"Lone Ranger, The	"});
good.push({name:"Loopz	"});
good.push({name:"Lost Word of Jenny	"});
good.push({name:"Lot Lot	"});
good.push({name:"Low G Man - The Low Gravity Man	"});
good.push({name:"Lu Ye Xian Zong	"});
good.push({name:"Lucky 777	"});
good.push({name:"Lunar Pool	"});
good.push({name:"Lupin Sansei - Pandora no Isan	"});
good.push({name:"M&M Heroes	"});
good.push({name:"M.C Kids	"});
good.push({name:"M.U.L.E.	"});
good.push({name:"M.U.S.C.L.E.	"});
good.push({name:"M82 Game Selectable Working Product Display	"});
good.push({name:"Ma Bu Mi Zhen & Qu Wei Cheng Yu Wu	"});
good.push({name:"Ma Li 12	"});
good.push({name:"Mach Rider	"});
good.push({name:"Mad Max	"});
good.push({name:"Mafat Conspiracy - Golgo 13	"});
good.push({name:"Magic Block	"});
good.push({name:"Magic Candle, The	"});
good.push({name:"Magic Cubes	"});
good.push({name:"Magic Darts	"});
good.push({name:"Magic Dragon	"});
good.push({name:"Magic Jewelry	"});
good.push({name:"Magic Jewelry 2	"});
good.push({name:"Magic Johnson's Fast Break	"});
good.push({name:"Magic Mathematic	"});
good.push({name:"Magic of Scheherazade, The	"});
good.push({name:"Magical Taruruuto-kun - Fantastic World!!	"});
good.push({name:"Magical Taruruuto-kun 2 - Mahou Daibouken	"});
good.push({name:"Magician	"});
good.push({name:"Magmax	"});
good.push({name:"Magnum Kiki Ippatsu - Empire City - 1931	"});
good.push({name:"Maharaja	"});
good.push({name:"Mahjan Samit Kabukicho Hen	"});
good.push({name:"Mahjang Companion	"});
good.push({name:"Mahjong	"});
good.push({name:"Mahjong Academy	"});
good.push({name:"Mahjong Block (MGC-008)	"});
good.push({name:"Mahjong Club - Nagatachou	"});
good.push({name:"Mahjong RPG Dora Dora Dora	"});
good.push({name:"Mahjong Taikai	"});
good.push({name:"Mahjong Taisen	"});
good.push({name:"Mahjong World	"});
good.push({name:"Mahou no Princess Minky Momo - Remember Dream	"});
good.push({name:"Maison Ikkoku	"});
good.push({name:"Majaventure - Mahjong Senki	"});
good.push({name:"Major League	"});
good.push({name:"Major League Baseball	"});
good.push({name:"Majou Densetsu II -Daimashikyou Galious	"});
good.push({name:"Makai Island	"});
good.push({name:"Maniac Mansion	"});
good.push({name:"Mappy	"});
good.push({name:"Mappy Kids	"});
good.push({name:"Mappy-Land	"});
good.push({name:"Marble Madness	"});
good.push({name:"Mario Bros.	"});
good.push({name:"Mario is Missing!	"});
good.push({name:"Mario's Time Machine!	"});
good.push({name:"Marusa no Onna	"});
good.push({name:"Mashin Eiyuu Den Wataru Gaiden	"});
good.push({name:"Master Chu & The Drunkard Hu	"});
good.push({name:"Master Shooter (CN-26)	"});
good.push({name:"Masuzoe Youichi - Asa Made Famicom	"});
good.push({name:"Matsumoto Tooru no Kabushiki Hisshou Gaku	"});
good.push({name:"Matsumoto Tooru no Kabushiki Hisshou Gaku 2	"});
good.push({name:"Mechanized Attack	"});
good.push({name:"Megaman	"});
good.push({name:"Megaman II	"});
good.push({name:"Megaman III	"});
good.push({name:"Megaman IV	"});
good.push({name:"Megaman V	"});
good.push({name:"Megaman VI	"});
good.push({name:"Mei Guo Fu Hao	"});
good.push({name:"Mei Nu Quan (Honey Peach)	"});
good.push({name:"Mei Tantei Holmes - Kiri no London Satsujin Jiken	"});
good.push({name:"Mei Tantei Holmes - M Kara no Chousenjou	"});
good.push({name:"Meiji Ishin	"});
good.push({name:"Meikyuu Jiin Dababa (FDS Conversion)	"});
good.push({name:"Meimon! Dai San Yakyuu Bu	"});
good.push({name:"Meimon! Takonishi Ouendan - Kouha 6 Nin Shuu	"});
good.push({name:"Melville's Flame	"});
good.push({name:"Menace Beach	"});
good.push({name:"Mendel Palace	"});
good.push({name:"Meng Huan	"});
good.push({name:"Metal Fighter	"});
good.push({name:"Metal Force	"});
good.push({name:"Metal Gear	"});
good.push({name:"Metal Max	"});
good.push({name:"Metal Mech - Man & Machine	"});
good.push({name:"Metal Slader Glory	"});
good.push({name:"Metal Storm	"});
good.push({name:"Metro-Cross	"});
good.push({name:"Metroid	"});
good.push({name:"Mezase Pachi Pro - Pachio-kun	"});
good.push({name:"Mezase Top Pro - Green ni Kakeru Yume	"});
good.push({name:"Mi Hun Che	"});
good.push({name:"Michael Andretti's World Grand Prix	"});
good.push({name:"Mickey Mania (Pirate)	"});
good.push({name:"Mickey Mousecapade	"});
good.push({name:"Mickey's Adventures in Numberland	"});
good.push({name:"Mickey's Safari in Letterland	"});
good.push({name:"Micro Machines	"});
good.push({name:"MiG 29 - Soviet Fighter	"});
good.push({name:"Might and Magic	"});
good.push({name:"Mighty Bomb Jack	"});
good.push({name:"Mighty Final Fight	"});
good.push({name:"Millionaire	"});
good.push({name:"Millipede	"});
good.push({name:"Milon's Secret Castle	"});
good.push({name:"Mind Blower Pak	"});
good.push({name:"Mindseeker	"});
good.push({name:"Minelvaton Saga	"});
good.push({name:"Mini Putt	"});
good.push({name:"Minna no Taabou no Nakayoshi Daisakusen	"});
good.push({name:"Miracle Piano Teaching System, The	"});
good.push({name:"Miracle Ropit's Adventure in 2100	"});
good.push({name:"Mirai Senshi - Lios	"});
good.push({name:"Mirai Shinwa Jarvas	"});
good.push({name:"Mission - Impossible	"});
good.push({name:"Mission Cobra	"});
good.push({name:"Mississippi Satsujin Jiken	"});
good.push({name:"Mito Koumon - Sekai Manyuu Ki	"});
good.push({name:"Mitsume ga Tooru	"});
good.push({name:"Mizushima Shinji no Dai Koushien	"});
good.push({name:"Mo Jie Ba Zhu	"});
good.push({name:"Moai-kun	"});
good.push({name:"Mobile Suit Z Gundam - Hot Scramble	"});
good.push({name:"Moero!! Juudou Warriors	"});
good.push({name:"Moeru! Oniisan	"});
good.push({name:"Momotarou Densetsu	"});
good.push({name:"Momotarou Densetsu Gaiden	"});
good.push({name:"Momotarou Dentetsu	"});
good.push({name:"Money Game 2 - Kabutochou no Kiseki, The	"});
good.push({name:"Money Game, The	"});
good.push({name:"Monopoly	"});
good.push({name:"Monster In My Pocket	"});
good.push({name:"Monster Maker - 7 Tsu no Hihou	"});
good.push({name:"Monster Party	"});
good.push({name:"Monster Truck Rally	"});
good.push({name:"Moon Crystal	"});
good.push({name:"Moon Ranger	"});
good.push({name:"Morita Kazuo no Shougi	"});
good.push({name:"Morskoy Boy	"});
good.push({name:"Mortal Kombat (Pirate)	"});
good.push({name:"Mortal Kombat Special (Pirate)	"});
good.push({name:"Mortal Kombat Variations (Pirates)	"});
good.push({name:"Motocross Champion	"});
good.push({name:"Motor City Patrol	"});
good.push({name:"Mottomo Abunai Deka	"});
good.push({name:"Mouryou Senki Madara	"});
good.push({name:"Mr. Gimmick	"});
good.push({name:"Ms. Pac-Man	"});
good.push({name:"Multi-Game Pirate Carts	"});
good.push({name:"Musashi no Bouken	"});
good.push({name:"Musashi no Ken - Tadaima Shugyou Chuu	"});
good.push({name:"Mutant Virus, The	"});
good.push({name:"My Life My Love - Boku no Yume - Watashi no Negai	"});
good.push({name:"Mystery Quest	"});
good.push({name:"Myth Struggle	"});
good.push({name:"Nagagutsu wo Haita Neko - Sekai Isshuu 80 Nichi Daibouken	"});
good.push({name:"Nakajima Satoru - F-1 Hero 2	"});
good.push({name:"Nakayoshi to Issho	"});
good.push({name:"Namco Classic	"});
good.push({name:"Namco Classic II	"});
good.push({name:"Namcot Mahjong 3 - Mahjong Tengoku	"});
good.push({name:"Nangoku Shirei!! - Spy Vs Spy	"});
good.push({name:"Nantettatte!! Baseball	"});
good.push({name:"Nantettatte!! Baseball '91 Kaimaku Hen	"});
good.push({name:"Nantettatte!! Baseball OB Allstar Hen	"});
good.push({name:"Napoleon Senki	"});
good.push({name:"Napoleon's War	"});
good.push({name:"NARC	"});
good.push({name:"Navy Blue	"});
good.push({name:"NBA Jam 2	"});
good.push({name:"Ne Zha Chuan Qi (NJ036)	"});
good.push({name:"Nekketsu Kakutou Densetsu	"});
good.push({name:"Nekketsu! Street Basket - Ganbare Dunk Heroes	"});
good.push({name:"NES Open Tournament Golf	"});
good.push({name:"NES Play Action Football	"});
good.push({name:"NES PowerPad Test Cart	"});
good.push({name:"NES Test Cart (Official Nintendo)	"});
good.push({name:"New Ghostbusters II	"});
good.push({name:"NFL Football	"});
good.push({name:"Nichibutsu Mahjong 3 - Mahjong G Men	"});
good.push({name:"Nigel Mansell's World Championship Challenge	"});
good.push({name:"Nightmare on Elm Street, A	"});
good.push({name:"Nightshade	"});
good.push({name:"Nihonichi no Mei Kantoku	"});
good.push({name:"Niji no Silk Road	"});
good.push({name:"Ninja Crusaders	"});
good.push({name:"Ninja Gaiden	"});
good.push({name:"Ninja Gaiden II - The Dark Sword of Chaos	"});
good.push({name:"Ninja Gaiden III - The Ancient Ship of Doom	"});
good.push({name:"Ninja Hattori-kun - Ninja wa Shuugyou de Gozaru no Maki	"});
good.push({name:"Ninja Jajamaru-kun	"});
good.push({name:"Ninja Kid	"});
good.push({name:"Ninja-kun - Ashura no Shou	"});
good.push({name:"Ninja-kun - Majou no Bouken	"});
good.push({name:"Ninjara Hoi!	"});
good.push({name:"Nintendo World Championships 1990	"});
good.push({name:"Nintendo World Cup	"});
good.push({name:"Nishimura Kyoutarou Mystery - Blue Train Satsujin Jiken	"});
good.push({name:"Nishimura Kyoutarou Mystery - Super Express Satsujin Jiken	"});
good.push({name:"Noah's Ark	"});
good.push({name:"Nobunaga no Yabou - Bushou Fuuun Roku	"});
good.push({name:"Nobunaga no Yabou - Zenkoku Ban	"});
good.push({name:"Nobunaga's Ambition	"});
good.push({name:"Nobunaga's Ambition 2	"});
good.push({name:"North & South	"});
good.push({name:"NTF2 System Cart	"});
good.push({name:"Nuts & Milk	"});
good.push({name:"Obocchama-kun	"});
good.push({name:"Ochin ni Toshi Puzzle Tonjan!	"});
good.push({name:"Oeka Kids - Anpanman no Hiragana Daisuki	"});
good.push({name:"Oeka Kids - Anpanman to Oekaki Shiyou!!	"});
good.push({name:"Oishinbo	"});
good.push({name:"Olympic IQ	"});
good.push({name:"Onyanko Town	"});
good.push({name:"Operation Secret Storm	"});
good.push({name:"Operation Wolf	"});
good.push({name:"Orb 3D	"});
good.push({name:"Osomatsu-kun	"});
good.push({name:"Otaku no Seiza - An Adventure in the Otaku Galaxy	"});
good.push({name:"Othello	"});
good.push({name:"Outlanders	"});
good.push({name:"Over Horizon	"});
good.push({name:"Overlord	"});
good.push({name:"P.O.W. - Prisoners of War	"});
good.push({name:"Paaman - Enban wo Torikaese!!	"});
good.push({name:"Paaman Part 2 - Himitsu Kessha Madoodan wo Taose!	"});
good.push({name:"Pachi Com	"});
good.push({name:"Pachinko Daisakusen	"});
good.push({name:"Pachinko Daisakusen 2	"});
good.push({name:"Pachio-kun 2	"});
good.push({name:"Pachio-kun 3	"});
good.push({name:"Pachio-kun 4	"});
good.push({name:"Pachio-kun 5	"});
good.push({name:"Pachi-Slot Adventure 2 - Sorotta-kun no Pachi Slot Tanteidan	"});
good.push({name:"Pachi-Slot Adventure 3 - Bitaoshii 7 Kenzan!	"});
good.push({name:"Pac-Land	"});
good.push({name:"Pac-Man	"});
good.push({name:"Pac-Mania	"});
good.push({name:"Palamedes	"});
good.push({name:"Palamedes 2 - Star Twinkles	"});
good.push({name:"Panda Prince, The (Pirate)	"});
good.push({name:"Panic Restaurant	"});
good.push({name:"Paperboy	"});
good.push({name:"Paperboy 2	"});
good.push({name:"Parallel World	"});
good.push({name:"Parasol Henbee	"});
good.push({name:"Parasol Stars - The Story of Bubble Bobble 3	"});
good.push({name:"Paris-Dakar Rally Special	"});
good.push({name:"Parodius	"});
good.push({name:"Peek-A-Boo Poker	"});
good.push({name:"Peepar Time	"});
good.push({name:"Penguin & Seal, The	"});
good.push({name:"Penguin-kun Wars	"});
good.push({name:"Perfect Bowling	"});
good.push({name:"Perfect Fit	"});
good.push({name:"Pescatore	"});
good.push({name:"Pesterminator - The Western Exterminator	"});
good.push({name:"Peter Pan & The Pirates	"});
good.push({name:"Phantom Air Mission	"});
good.push({name:"Phantom Fighter	"});
good.push({name:"Pi Nuo Cao De Fu Su	"});
good.push({name:"Pictionary	"});
good.push({name:"Pin Bot	"});
good.push({name:"Pinball	"});
good.push({name:"Pinball Quest	"});
good.push({name:"Pipe 5	"});
good.push({name:"Pipe Dream	"});
good.push({name:"Pirates!	"});
good.push({name:"Pizza Pop!	"});
good.push({name:"Plasma Ball	"});
good.push({name:"Platoon	"});
good.push({name:"Po Po Team	"});
good.push({name:"Pocahontas (Pirate)	"});
good.push({name:"Pocahontas 2 (Pirate)	"});
good.push({name:"Pocket Monster (Pirate)	"});
good.push({name:"Pocket Monsters Red	"});
good.push({name:"Pocket Zaurus - Juu Ouken no Nazo	"});
good.push({name:"Poke Block	"});
good.push({name:"Poke Tetris	"});
good.push({name:"Pokemon Gold (Pirate)	"});
good.push({name:"Poker II	"});
good.push({name:"Poker III	"});
good.push({name:"Poker Mahjong	"});
good.push({name:"Pole Chudes	"});
good.push({name:"Pole Chudes 2	"});
good.push({name:"Pooyan	"});
good.push({name:"Popeye	"});
good.push({name:"Popeye no Eigo Asobi	"});
good.push({name:"Port Test Cartridge	"});
good.push({name:"Portopia Renzoku Satsujin Jiken	"});
good.push({name:"Power Blade	"});
good.push({name:"Power Blade 2	"});
good.push({name:"Power Blazer	"});
good.push({name:"Power Punch 2	"});
good.push({name:"Power Rangers III (Pirate)	"});
good.push({name:"Power Soccer	"});
good.push({name:"P'radikus Conflict, The	"});
good.push({name:"Pravila Dorozhnogo Dvizheniya	"});
good.push({name:"Predator	"});
good.push({name:"President no Sentaku	"});
good.push({name:"Prince of Persia	"});
good.push({name:"Princess Tomato in Salad Kingdom	"});
good.push({name:"Pro Action Replay	"});
good.push({name:"Pro Sport Hockey	"});
good.push({name:"Pro Wrestling	"});
good.push({name:"Pro Yakyuu Satsujin Jiken!	"});
good.push({name:"Project Q	"});
good.push({name:"Public Domain	"});
good.push({name:"Punch-Out!!	"});
good.push({name:"Punisher, The	"});
good.push({name:"Puss 'n Boots - Pero's Great Adventure	"});
good.push({name:"Puteshestvie po Evropa	"});
good.push({name:"Puyo Puyo	"});
good.push({name:"Puzslot	"});
good.push({name:"Puzzle	"});
good.push({name:"Puzznic	"});
good.push({name:"Pyokotan no Dai Meiro	"});
good.push({name:"Pyramid	"});
good.push({name:"Pyramid II	"});
good.push({name:"Q Boy	"});
good.push({name:"Q-bert	"});
good.push({name:"Qi Guo Da Zhan (NJ029)	"});
good.push({name:"Qi Wang - Chinese Chess	"});
good.push({name:"Qix	"});
good.push({name:"Quarter Back Scramble	"});
good.push({name:"Quarth	"});
good.push({name:"Quattro Adventure	"});
good.push({name:"Quattro Arcade	"});
good.push({name:"Quattro Sports	"});
good.push({name:"Quest of Ki, The	"});
good.push({name:"R.B.I. Baseball	"});
good.push({name:"R.B.I. Baseball 2	"});
good.push({name:"R.B.I. Baseball 3	"});
good.push({name:"R.C. Pro-Am	"});
good.push({name:"R.C. Pro-Am II	"});
good.push({name:"Race America	"});
good.push({name:"Racer Mini Yonku - Japan Cup	"});
good.push({name:"Racermate Challenger II V6.02.002	"});
good.push({name:"Racket Attack	"});
good.push({name:"Rackets & Rivals	"});
good.push({name:"Rad Racer	"});
good.push({name:"Rad Racer 2	"});
good.push({name:"Rad Racket - Deluxe Tennis II	"});
good.push({name:"Radia Senki - Reimei Hen	"});
good.push({name:"Raid 2020	"});
good.push({name:"Raid on Bungeling Bay	"});
good.push({name:"Rainbow Islands - The Story of Bubble Bobble 2	"});
good.push({name:"Rally Bike	"});
good.push({name:"Rambo	"});
good.push({name:"Rampage	"});
good.push({name:"Rampart	"});
good.push({name:"Rasaaru Ishii no Childs Quest	"});
good.push({name:"Remote Control	"});
good.push({name:"Ren & Stimpy Show, The	"});
good.push({name:"Renegade	"});
good.push({name:"Rescue - The Embassy Mission	"});
good.push({name:"Ring King	"});
good.push({name:"River City Ransom	"});
good.push({name:"Road Fighter	"});
good.push({name:"Road Runner	"});
good.push({name:"RoadBlasters	"});
good.push({name:"Robin Hood - Prince of Thieves	"});
good.push({name:"Robo Warrior	"});
good.push({name:"Robocco Wars	"});
good.push({name:"RoboCop	"});
good.push({name:"RoboCop 2	"});
good.push({name:"RoboCop 3	"});
good.push({name:"RoboCop Vs The Terminator	"});
good.push({name:"Robodemons	"});
good.push({name:"Rock 'n' Ball	"});
good.push({name:"Rockball	"});
good.push({name:"Rocket Ranger	"});
good.push({name:"Rocketeer, The	"});
good.push({name:"Rockin' Kats	"});
good.push({name:"Rocman X (aka Thunder Blaster Man)	"});
good.push({name:"Rod Land	"});
good.push({name:"Roger Clemens' MVP Baseball	"});
good.push({name:"Rokudenashi Blues	"});
good.push({name:"Rollerball	"});
good.push({name:"Rollerblade Racer	"});
good.push({name:"Rollergames	"});
good.push({name:"Rolling Thunder	"});
good.push({name:"Romance of The Three Kingdoms	"});
good.push({name:"Romance of The Three Kingdoms II	"});
good.push({name:"Romancia	"});
good.push({name:"Roundball - 2-on-2 Challenge	"});
good.push({name:"Route 16 Turbo	"});
good.push({name:"RPG Jinsei Game	"});
good.push({name:"Rush'n Attack	"});
good.push({name:"Rygar	"});
good.push({name:"S.C.A.T. - Special Cybernetic Attack Team	"});
good.push({name:"Saint Saiya - Tian Ma Huan Xiang	"});
good.push({name:"Saint Seiya - Ougon Densetsu	"});
good.push({name:"Saint Seiya - Ougon Densetsu Kanketsu Hen	"});
good.push({name:"Saiyuuki World	"});
good.push({name:"Sakigake!! Otoko Juku - Shippuu Ichi Gou Sei	"});
good.push({name:"Samurai Spirits (Pirate)	"});
good.push({name:"San Guo Zhi - CaoCao Zhuan (NJ018)	"});
good.push({name:"San Guo Zhi - Qun Xiong Zheng Ba	"});
good.push({name:"San Guo Zhi 2	"});
good.push({name:"San Guo Zhi 4 - Chi Bi Feng Yun	"});
good.push({name:"San Guo Zhong Lie Zhuan	"});
good.push({name:"San Shi Liu Ji	"});
good.push({name:"Sanada Juu Yuushi	"});
good.push({name:"Sangokushi - Chuugen no Hasha	"});
good.push({name:"Sangokushi II - Haou no Tairiku	"});
good.push({name:"Sanma no Mei Tantei	"});
good.push({name:"Sanrio Carnival	"});
good.push({name:"Sanrio Carnival 2	"});
good.push({name:"Sanrio Cup - Pon Pon Volley	"});
good.push({name:"Sansara Naga	"});
good.push({name:"Sansuu 1 Nen - Keisan Game	"});
good.push({name:"Sansuu 2 Nen - Keisan Game	"});
good.push({name:"Sansuu 3 Nen - Keisan Game	"});
good.push({name:"Sansuu 4 Nen - Keisan Game	"});
good.push({name:"Sansuu 5 & 6 Nen - Keisan Game	"});
good.push({name:"Satomi Hakkenden	"});
good.push({name:"Satsui no Kaisou - Power Soft Satsujin Jiken	"});
good.push({name:"Satsujin Club	"});
good.push({name:"Scarabeus	"});
good.push({name:"SD Battle Oozumou - Heisei Hero Basho	"});
good.push({name:"SD Gundam - Gachapon Senshi 2 - Capsule Senki	"});
good.push({name:"SD Gundam - Gachapon Senshi 3 - Eiyuu Senki	"});
good.push({name:"SD Gundam - Gachapon Senshi 4 - New Type Story	"});
good.push({name:"SD Gundam - Gachapon Senshi 5 - Battle of Universal Century	"});
good.push({name:"SD Gundam Gaiden - Knight Gundam Monogatari	"});
good.push({name:"SD Gundam Gaiden - Knight Gundam Monogatari 2 - Hikari no Kishi	"});
good.push({name:"SD Gundam Gaiden - Knight Gundam Monogatari 3 - Densetsu no Kishi Dan	"});
good.push({name:"SD Hero Soukessen - Taose! Aku no Gundan	"});
good.push({name:"SD Keiji - Blader	"});
good.push({name:"SD Sengoku Bushou Retsuden	"});
good.push({name:"Sea of Dreamland	"});
good.push({name:"Secret Scout in the Temple of Demise	"});
good.push({name:"Secret Ties	"});
good.push({name:"Section Z	"});
good.push({name:"Seicross	"});
good.push({name:"Seikima II - Akuma no Gyakushuu	"});
good.push({name:"Seirei Gari	"});
good.push({name:"Seiryaku Simulation - Inbou no Wakusei - Shancara	"});
good.push({name:"Sekiryuuou	"});
good.push({name:"Sesame Street 123	"});
good.push({name:"Sesame Street 123 - ABC	"});
good.push({name:"Sesame Street ABC	"});
good.push({name:"Sesame Street Countdown	"});
good.push({name:"Shadow Brain	"});
good.push({name:"Shadow of the Ninja	"});
good.push({name:"Shadowgate	"});
good.push({name:"Shaffle Fight	"});
good.push({name:"Shang Gu Shen Jian	"});
good.push({name:"Shanghai	"});
good.push({name:"Shanghai 2	"});
good.push({name:"Shanghai Tycoon	"});
good.push({name:"Shatterhand	"});
good.push({name:"Shen Hua Jian Yun III	"});
good.push({name:"Shen Tan Ke Nan	"});
good.push({name:"Sheng Hen Pao (AKA Twin Loud Cannon)	"});
good.push({name:"Sheng Huo Lie Zhuan	"});
good.push({name:"Sherlock Holmes - Hakushaku Reijou Yuukai Jiken	"});
good.push({name:"Shikinjou	"});
good.push({name:"Shin 4 Nin Uchi Mahjong - Yakuman Tengoku	"});
good.push({name:"Shin Moero!! Pro Yakyuu	"});
good.push({name:"Shin Samurai Spirits 2 - Haoumaru Jigoku Hen	"});
good.push({name:"Shin Satomi Hakken-Den - Hikari to Yami no Tatakai	"});
good.push({name:"Shingen The Ruler	"});
good.push({name:"Shinobi	"});
good.push({name:"Shinsenden	"});
good.push({name:"Shisen Mahjong	"});
good.push({name:"Shisen Mahjong - Seifuku Hen	"});
good.push({name:"Shisen Mahjong 2	"});
good.push({name:"Shockwave	"});
good.push({name:"Shooting Range	"});
good.push({name:"Short Order - Eggsplode	"});
good.push({name:"Shougi Meikan '92	"});
good.push({name:"Shougi Meikan '93	"});
good.push({name:"Shougun	"});
good.push({name:"Shoukoushi Ceddie	"});
good.push({name:"Shounen Ashibe - Nepal Daibouken no Maki	"});
good.push({name:"Shu Qi Yu - Zhi Li Xiao Zhuan Yuan	"});
good.push({name:"Shufflepuck Cafe	"});
good.push({name:"Shui Guan Pipe	"});
good.push({name:"Shui Guo Li	"});
good.push({name:"Shui Hu Shen Shou (NJ019)	"});
good.push({name:"Shui Hu Zhuan	"});
good.push({name:"Si Lu Chuan Qi	"});
good.push({name:"Side Pocket	"});
good.push({name:"Sidewinder	"});
good.push({name:"Silent Assault	"});
good.push({name:"Silent Service	"});
good.push({name:"Silkworm	"});
good.push({name:"Silva Saga	"});
good.push({name:"Silver Eagle	"});
good.push({name:"Silver Surfer	"});
good.push({name:"Simpsons, The - Bart Vs. the Space Mutants	"});
good.push({name:"Simpsons, The - Bart Vs. the World	"});
good.push({name:"Simpsons, The - Bartman Meets Radioactive Man	"});
good.push({name:"Skate or Die 2 - The Search for Double Trouble	"});
good.push({name:"Skate or Die!	"});
good.push({name:"Ski or Die	"});
good.push({name:"Skull & Crossbones	"});
good.push({name:"Sky Destroyer	"});
good.push({name:"Sky Kid	"});
good.push({name:"Sky Shark	"});
good.push({name:"Slalom	"});
good.push({name:"Smash Ping Pong	"});
good.push({name:"Smash T.V.	"});
good.push({name:"Smurfs, The	"});
good.push({name:"Snake Rattle N Roll	"});
good.push({name:"Snake's Revenge	"});
good.push({name:"Snoopy's Silly Sports Spectacular	"});
good.push({name:"Snow Brothers	"});
good.push({name:"Snowboard Challenge	"});
good.push({name:"Soccer	"});
good.push({name:"Soccer League - Winner's Cup	"});
good.push({name:"Solar Jetman - Hunt for the Golden Warpship	"});
good.push({name:"Solitaire	"});
good.push({name:"Solomon's Key	"});
good.push({name:"Solstice - The Quest for the Staff of Demnos	"});
good.push({name:"Son Son	"});
good.push({name:"Sonic 3D Blast (Pirate)	"});
good.push({name:"Sonic The Hedgehog (Pirate)	"});
good.push({name:"Sore Ike! Anapanman - Minna de Hiking Game!	"});
good.push({name:"Space Boy	"});
good.push({name:"Space Harrier	"});
good.push({name:"Space Hunter	"});
good.push({name:"Space Invaders	"});
good.push({name:"Space Shadow	"});
good.push({name:"Space Shuttle Project	"});
good.push({name:"Spartan X 2	"});
good.push({name:"Spelunker	"});
good.push({name:"Spelunker 2 - Yuusha heno Chousen	"});
good.push({name:"Spider-Man - Return of the Sinister Six	"});
good.push({name:"Spiderman 2	"});
good.push({name:"Spiritual Warfare	"});
good.push({name:"Splatter House - Wanpaku Graffiti	"});
good.push({name:"Spot	"});
good.push({name:"Spy Hunter	"});
good.push({name:"Spy Vs Spy	"});
good.push({name:"Sqoon	"});
good.push({name:"Square Force	"});
good.push({name:"Square no Tom Sawyer	"});
good.push({name:"Squashed	"});
good.push({name:"Stack Up (Block Set)	"});
good.push({name:"Stadium Events	"});
good.push({name:"Stanley - The Search for Dr. Livingston	"});
good.push({name:"Star Force	"});
good.push({name:"Star Luster	"});
good.push({name:"Star Soldier	"});
good.push({name:"Star Trek - 25th Anniversary	"});
good.push({name:"Star Trek - The Next Generation	"});
good.push({name:"Star Trek V - The Final Frontier	"});
good.push({name:"Star Voyager	"});
good.push({name:"Star Wars - The Empire Strikes Back	"});
good.push({name:"Star Wars (JVC)	"});
good.push({name:"Star Wars (Namco)	"});
good.push({name:"Starship Hector	"});
good.push({name:"Startropics	"});
good.push({name:"Startropics II - Zoda's Revenge	"});
good.push({name:"Stealth ATF	"});
good.push({name:"Sted - Iseki Wakusei no Yabou	"});
good.push({name:"Stick Hunter - Exciting Ice Hockey	"});
good.push({name:"Stinger	"});
good.push({name:"Strategist	"});
good.push({name:"Street Cop	"});
good.push({name:"Street Fighter 2010 - The Final Fight	"});
good.push({name:"Street Fighter II (Pirate)	"});
good.push({name:"Street Fighter III (Pirate)	"});
good.push({name:"Street Fighter IV (Pirate)	"});
good.push({name:"Street Fighter V (Pirate)	"});
good.push({name:"Street Fighter Zero 2 (Pirate)	"});
good.push({name:"Street Heroes	"});
good.push({name:"Strider	"});
good.push({name:"Strike Wolf (MGC-014)	"});
good.push({name:"Stroke & Match Golf	"});
good.push({name:"Study Box (Fukutake Shoten)	"});
good.push({name:"Stunt Kids	"});
good.push({name:"Subor Figure Ratiocination & IQ Puzzle	"});
good.push({name:"Subor V1.0	"});
good.push({name:"Subor V3.0	"});
good.push({name:"Subor V4.0	"});
good.push({name:"Sugoro Quest - Dice no Senshitachi	"});
good.push({name:"SuiTang	"});
good.push({name:"Sukeban Deka 3	"});
good.push({name:"Summer Carnival '92 - Recca	"});
good.push({name:"Sunday Funday	"});
good.push({name:"Sunman	"});
good.push({name:"Super Arabian	"});
good.push({name:"Super Black Onyx	"});
good.push({name:"Super C	"});
good.push({name:"Super Cars	"});
good.push({name:"Super Chinese 3	"});
good.push({name:"Super Contra 7 (Pirate)	"});
good.push({name:"Super Contra X (Pirate)	"});
good.push({name:"Super Dodge Ball	"});
good.push({name:"Super Donkey Kong - Xiang Jiao Chuan (Pirate)	"});
good.push({name:"Super Donkey Kong (Pirate)	"});
good.push({name:"Super Donkey Kong 2 (Pirate)	"});
good.push({name:"Super Dyna'mix Badminton	"});
good.push({name:"Super Glove Ball	"});
good.push({name:"Super Jeopardy!	"});
good.push({name:"Super Mario Bros.	"});
good.push({name:"Super Mario Bros. - Hack Collection	"});
good.push({name:"Super Mario Bros. + Duck Hunt	"});
good.push({name:"Super Mario Bros. + Duck Hunt + World Class Track Meet	"});
good.push({name:"Super Mario Bros. + Tetris + Nintendo World Cup	"});
good.push({name:"Super Mario Bros. 2 (J)	"});
good.push({name:"Super Mario Bros. 2 (U)	"});
good.push({name:"Super Mario Bros. 2 (U) - Hack Collection	"});
good.push({name:"Super Mario Bros. 3	"});
good.push({name:"Super Mario Bros. 3 - Hack Collection	"});
good.push({name:"Super Mario World (Pirate)	"});
good.push({name:"Super Mogura Tataki!! - Pokkun Moguraa	"});
good.push({name:"Super Momotarou Dentetsu	"});
good.push({name:"Super Pang	"});
good.push({name:"Super Pang 2	"});
good.push({name:"Super Pinball	"});
good.push({name:"Super Pitfall	"});
good.push({name:"Super Real Baseball '88	"});
good.push({name:"Super Rugby	"});
good.push({name:"Super Shinobi, The	"});
good.push({name:"Super Sonic 5 (Pirate)	"});
good.push({name:"Super Spike V'Ball	"});
good.push({name:"Super Spike V'Ball + Nintendo World Cup	"});
good.push({name:"Super Sprint	"});
good.push({name:"Super Spy Hunter	"});
good.push({name:"Super Star Force	"});
good.push({name:"Super Team Games	"});
good.push({name:"Super Turrican	"});
good.push({name:"Super Xevious - Gump no Nazo	"});
good.push({name:"Superman	"});
good.push({name:"Swamp Thing	"});
good.push({name:"SWAT - Special Weapons and Tactics	"});
good.push({name:"Sweet Home	"});
good.push({name:"Sword Master	"});
good.push({name:"Swords and Serpents	"});
good.push({name:"T&C 2 - Thrilla's Surfari	"});
good.push({name:"T&C Surf Design	"});
good.push({name:"Taboo - The Sixth Sense	"});
good.push({name:"Tag Team Wrestling	"});
good.push({name:"Tagin' Dragon	"});
good.push({name:"Tai Kong Huan Xiang (NJ016)	"});
good.push({name:"Taito Chase H.Q.	"});
good.push({name:"Taito Grand Prix - Eikou heno License	"});
good.push({name:"Taiwan Mahjong 16	"});
good.push({name:"Taiwan Mahjong 2	"});
good.push({name:"Taiyou no Yuusha Firebird	"});
good.push({name:"Takahashi Meijin no Bouken Shima IV	"});
good.push({name:"Takahashi Meijin no Bugutte Honey	"});
good.push({name:"Takeda Shingen	"});
good.push({name:"Takeshi no Chousenjou	"});
good.push({name:"Takeshi no Sengoku Fuuunji	"});
good.push({name:"TaleSpin	"});
good.push({name:"Tamura Koushou Mahjong Seminar	"});
good.push({name:"Tang Bo Hu Dian Qiu Xiang (NJ069)	"});
good.push({name:"Tang Mu Li Xian Ji	"});
good.push({name:"Tanigawa Kouji no Shougi Shinan 3	"});
good.push({name:"Tanigawa Kouji no Shougi Shinan II	"});
good.push({name:"Tantei Jinguuji Saburou - Toki no Sugiyuku Mama ni	"});
good.push({name:"Tantei Jinguuji Saburou - Yokohamakou Renzoku Satsujin Jiken	"});
good.push({name:"Tao	"});
good.push({name:"Target - Renegade	"});
good.push({name:"Taro's Quest	"});
good.push({name:"Tasac	"});
good.push({name:"Tashiro Masashi no Princess ga Ippai	"});
good.push({name:"Tatakae! Chou Robotto Seimeitai Transformers - Convoy no Nazo	"});
good.push({name:"Tatakae!! Rahmen Man - Sakuretsu Choujin 102 Gei	"});
good.push({name:"Tecmo Baseball	"});
good.push({name:"Tecmo Bowl	"});
good.push({name:"Tecmo Cup - Soccer Game	"});
good.push({name:"Tecmo NBA Basketball	"});
good.push({name:"Tecmo Super Bowl	"});
good.push({name:"Tecmo World Cup Soccer	"});
good.push({name:"Tecmo World Wrestling	"});
good.push({name:"Teenage Mutant Ninja Turtles	"});
good.push({name:"Teenage Mutant Ninja Turtles - Tournament Fighters	"});
good.push({name:"Teenage Mutant Ninja Turtles II - The Arcade Game	"});
good.push({name:"Teenage Mutant Ninja Turtles III - The Manhattan Project	"});
good.push({name:"Tekken 2	"});
good.push({name:"Tekken 3	"});
good.push({name:"Tenchi wo Kurau II - Shokatsu Koumei Den	"});
good.push({name:"Tenka no Goikenban - Mito Koumon	"});
good.push({name:"Tenkaichi Bushi - Keru Naguuru	"});
good.push({name:"Tennis	"});
good.push({name:"Terao no Dosukoi Oozumou	"});
good.push({name:"Terminator 2 - Judgment Day	"});
good.push({name:"Terminator, The	"});
good.push({name:"Terra Cresta	"});
good.push({name:"Tetrastar - The Fighter	"});
good.push({name:"Tetris	"});
good.push({name:"Tetris 2	"});
good.push({name:"Tetris 2 + BomBliss	"});
good.push({name:"Tetsudou Ou - Famicom Boardgame	"});
good.push({name:"Tetsuwan Atom	"});
good.push({name:"Text Editor	"});
good.push({name:"Thexder	"});
good.push({name:"Thomas the Tank Engine and Friends	"});
good.push({name:"Three Stooges	"});
good.push({name:"Thunder & Lightning	"});
good.push({name:"Thunder Warrior	"});
good.push({name:"Thunderbirds	"});
good.push({name:"Thunderbolt 2	"});
good.push({name:"Thundercade	"});
good.push({name:"Tiger-Heli	"});
good.push({name:"Tiles of Fate	"});
good.push({name:"Time Diver Avenger	"});
good.push({name:"Time Diver Eon Man	"});
good.push({name:"Time Lord	"});
good.push({name:"Time Zone	"});
good.push({name:"Times of Lore	"});
good.push({name:"Tin Choi Ma Lei	"});
good.push({name:"Tiny Toon Adventures	"});
good.push({name:"Tiny Toon Adventures 2 - Trouble in Wackyland	"});
good.push({name:"Tiny Toon Adventures 6	"});
good.push({name:"Tiny Toon Adventures Cartoon Workshop	"});
good.push({name:"Titan	"});
good.push({name:"Titan Warriors	"});
good.push({name:"Titanic (NJ031)	"});
good.push({name:"Titanic 1912	"});
good.push({name:"TM Network - Live in Power Bowl	"});
good.push({name:"To The Earth	"});
good.push({name:"Tobidase Daisakusen (FDS Conversion)	"});
good.push({name:"Toita Basketball	"});
good.push({name:"Toki	"});
good.push({name:"Toki no Tabibito	"});
good.push({name:"Tokoro San no Mamoru mo Semeru mo	"});
good.push({name:"Tom & Jerry	"});
good.push({name:"Tom & Jerry 3	"});
good.push({name:"Tombs & Treasure	"});
good.push({name:"Toobin'	"});
good.push({name:"Top Gun	"});
good.push({name:"Top Gun - The Second Mission	"});
good.push({name:"Top Gun III	"});
good.push({name:"Top Players' Tennis - Featuring Chris Evert & Ivan Lendl	"});
good.push({name:"Top Rider	"});
good.push({name:"Top Striker	"});
good.push({name:"Total Recall	"});
good.push({name:"Totally Rad	"});
good.push({name:"Touch Down Fever	"});
good.push({name:"Touhou Kenbun Roku	"});
good.push({name:"Toukon Club	"});
good.push({name:"Toukyou Pachi Slot Adventure	"});
good.push({name:"Tower of Druaga, The	"});
good.push({name:"Toxic Crusaders	"});
good.push({name:"Toy Story	"});
good.push({name:"Track & Field	"});
good.push({name:"Track & Field II	"});
good.push({name:"Treasure Master	"});
good.push({name:"Triathron, The	"});
good.push({name:"Trog	"});
good.push({name:"Trojan	"});
good.push({name:"Trolls in Crazyland, The	"});
good.push({name:"Trolls on Treasure Island	"});
good.push({name:"Tsuppari Oozumou	"});
good.push({name:"Tsuppari Wars	"});
good.push({name:"Tsuri Kichi Sanpei - Blue Marlin Hen	"});
good.push({name:"Tsuru Pika Hagemaru - Mezase! Tsuru Seko no Akashi	"});
good.push({name:"Tui Do Woo Ma Jeung	"});
good.push({name:"Twin Cobra	"});
good.push({name:"Twin Eagle	"});
good.push({name:"TwinBee	"});
good.push({name:"TwinBee 3 - Poko Poko Dai Maou	"});
good.push({name:"Uchuu Keibitai SDF	"});
good.push({name:"Uchuusen - Cosmo Carrier	"});
good.push({name:"U-Force Test Cartridge	"});
good.push({name:"U-four-ia - The Saga	"});
good.push({name:"Ugadayka	"});
good.push({name:"Ultima - Exodus	"});
good.push({name:"Ultima - Quest of the Avatar	"});
good.push({name:"Ultima - Warriors of Destiny	"});
good.push({name:"Ultimate Air Combat	"});
good.push({name:"Ultimate Basketball	"});
good.push({name:"Ultimate League Soccer	"});
good.push({name:"Ultimate Stuntman	"});
good.push({name:"Ultraman Club - Kaijuu Dai Kessen!!	"});
good.push({name:"Ultraman Club 2 - Kaettekita Ultraman Club	"});
good.push({name:"Ultraman Club 3	"});
good.push({name:"Um Chi (Glommy Chess)	"});
good.push({name:"Uncanny X-Men, The	"});
good.push({name:"Uncharted Waters	"});
good.push({name:"Uninvited	"});
good.push({name:"Universe Soldiers, The	"});
good.push({name:"Untouchables, The	"});
good.push({name:"Urban Champion	"});
good.push({name:"Urban Strike	"});
good.push({name:"Urusei Yatsura - Lum no Wedding Bell	"});
good.push({name:"Ushio to Tora - Shinen no Daiyou	"});
good.push({name:"Utsurun Desu	"});
good.push({name:"Valis - The Fantastic Soldier	"});
good.push({name:"Valkyrie no Bouken - Toki no Kagi Densetsu	"});
good.push({name:"Vegas Connection - Casino Kara Ai wo Komete	"});
good.push({name:"Vegas Dream	"});
good.push({name:"Venice Beach Volleyball	"});
good.push({name:"Venus Senki	"});
good.push({name:"Vice - Project Doom	"});
good.push({name:"Videomation	"});
good.push({name:"Vindicators	"});
good.push({name:"Volguard II	"});
good.push({name:"Volleyball	"});
good.push({name:"Volshebnaya Palitra	"});
good.push({name:"Wa Di Lei (Minesweeper)	"});
good.push({name:"Wacky Races	"});
good.push({name:"Wagyan Land	"});
good.push({name:"Wagyan Land 2	"});
good.push({name:"Wagyan Land 3	"});
good.push({name:"Wai Wai World	"});
good.push({name:"Wai Wai World 2 - SOS!! Paseri Jou	"});
good.push({name:"Wai Xing Zhan Shi	"});
good.push({name:"Wai Xing Zhan Shi 2	"});
good.push({name:"Wait and See!	"});
good.push({name:"Wall Street Kid	"});
good.push({name:"Wally Bear & the No Gang	"});
good.push({name:"Wang Zi Fu Chou Ji	"});
good.push({name:"Warehouse No. 18	"});
good.push({name:"Wario's Woods	"});
good.push({name:"Warpman	"});
good.push({name:"Wayne Gretzky Hockey	"});
good.push({name:"Wayne's World	"});
good.push({name:"WCW World Championship Wrestling	"});
good.push({name:"Wei Luo Chuan Qi	"});
good.push({name:"Werewolf - The Last Warrior	"});
good.push({name:"Wheel of Fortune	"});
good.push({name:"Wheel of Fortune - Starring Vanna White	"});
good.push({name:"Where in Time is Carmen Sandiego	"});
good.push({name:"Where's Waldo	"});
good.push({name:"Who Framed Roger Rabbit	"});
good.push({name:"Whomp'Em	"});
good.push({name:"WideBoy Rev B (iNES Version)	"});
good.push({name:"Widget	"});
good.push({name:"Wild Gunman	"});
good.push({name:"Willow	"});
good.push({name:"Wily & Light no Rockboard - That's Paradise	"});
good.push({name:"Win, Lose or Draw	"});
good.push({name:"Wing of Madoola, The	"});
good.push({name:"Winter Games	"});
good.push({name:"Wisdom Boy	"});
good.push({name:"Wit's	"});
good.push({name:"Wizardry - Proving Grounds of the Mad Overlord	"});
good.push({name:"Wizardry - The Knight of Diamonds	"});
good.push({name:"Wizardry II - Llylgamyn no Densetsu	"});
good.push({name:"Wizards & Warriors	"});
good.push({name:"Wizards & Warriors III - Kuros - Visions of Power	"});
good.push({name:"Wolverine	"});
good.push({name:"Woody Poko	"});
good.push({name:"World Boxing	"});
good.push({name:"World Champ	"});
good.push({name:"World Games	"});
good.push({name:"World Hero	"});
good.push({name:"World Heroes 2	"});
good.push({name:"World of Card Game, The	"});
good.push({name:"Wrath of the Black Manta	"});
good.push({name:"Wrecking Crew	"});
good.push({name:"Wrecking Crew 2004	"});
good.push({name:"Wu Shi Hun	"});
good.push({name:"WURM - Journey to the Center of the Earth	"});
good.push({name:"WWF King of the Ring	"});
good.push({name:"WWF WrestleMania	"});
good.push({name:"WWF WrestleMania - Steel Cage Challenge	"});
good.push({name:"WWF WrestleMania Challenge	"});
good.push({name:"Xenophobe	"});
good.push({name:"Xevious	"});
good.push({name:"Xexyz	"});
good.push({name:"Xi Tian Qu Jing II	"});
good.push({name:"Xia Ke Qing - Jing He Ci Qin Wang	"});
good.push({name:"Xian Jian Qi Xia Zhuan	"});
good.push({name:"Xiao Au Jiang Wu	"});
good.push({name:"Xiao Ma Li	"});
good.push({name:"Xing He Zhan Shi	"});
good.push({name:"Xing Ji Wu Shi - Super Fighter	"});
good.push({name:"Xing Ji Zheng Ba	"});
good.push({name:"Xing Zhan Qing Yuan	"});
good.push({name:"Xybots	"});
good.push({name:"Yamamura Misa Suspense - Kyouto Hana no Misshitsu Satsujin Jiken	"});
good.push({name:"Yamamura Misa Suspense - Kyouto Ryuu no Tera Satsujin Jiken	"});
good.push({name:"Yamamura Misa Suspense - Kyouto Zaiteku Satsujin Jiken	"});
good.push({name:"Yang Jia Jiang - Yang's Troops	"});
good.push({name:"Yanshan Chess	"});
good.push({name:"Yie Ar Kung-Fu	"});
good.push({name:"Ying Lie Qun Xia Zhuan	"});
good.push({name:"Ying Xiong Chuan Qi	"});
good.push({name:"Ying Xiong Yuan Yi Jing Chuan Qi	"});
good.push({name:"Yo! Noid	"});
good.push({name:"Yoshi	"});
good.push({name:"Yoshi's Cookie	"});
good.push({name:"You Ling Xing Dong	"});
good.push({name:"Youkai Douchuuki	"});
good.push({name:"Youkai Kurabu	"});
good.push({name:"Young Chivalry	"});
good.push({name:"Young Indiana Jones Chronicles, The	"});
good.push({name:"Ys	"});
good.push({name:"Ys II - Ancient Ys Vanished - The Final Chapter	"});
good.push({name:"Ys III - Wanderers From Ys	"});
good.push({name:"Yuefei	"});
good.push({name:"Yu-Gi-Oh (NJ032)	"});
good.push({name:"Yume Penguin Monogatari	"});
good.push({name:"Yuu Yuu Hakusho Final - Makai Saikyou Retsuden	"});
good.push({name:"Zanac	"});
good.push({name:"Zelda - Shen Qi De Mao Zi	"});
good.push({name:"Zelda II - The Adventure of Link	"});
good.push({name:"Zen - Intergalactic Ninja	"});
good.push({name:"Zhan Guo Qun Xiong Zhuan	"});
good.push({name:"Zhan Guo Wu Shuang	"});
good.push({name:"Zhen Ben Xi You Ji	"});
good.push({name:"Zhong Guo Xiang Qi	"});
good.push({name:"Zhong Guo Xiang Qi (Chinese Chess)	"});
good.push({name:"Zippy Race	"});
good.push({name:"Zoids - Chuuou Tairiku no Tatakai	"});
good.push({name:"Zoids 2 - Zenebas no Gyakushuu	"});
good.push({name:"Zoids Mokushiroku	"});
good.push({name:"Zombie Hunter	"});
good.push({name:"Zombie Nation	"});
good.push({name:"Zu Qiu Xiao Jiang	"});
good.push({name:"Zunou Senkan Galg	"});
